import { LandingNav } from "@/components/landing/landing-nav";
import { LandingFooter } from "@/components/landing/landing-footer";

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-[#FAF8F4] text-[#0F0F0F]">
      <LandingNav />
      
      <article className="mx-auto max-w-3xl px-6 py-20 md:py-32">
        <header className="mb-16">
          <h1 className="text-4xl font-extrabold tracking-tight md:text-5xl">
            Terms of Service
          </h1>
          <p className="mt-4 text-sm font-medium text-[#6B6B6B]">
            Effective Date: April 13, 2026
          </p>
        </header>

        <div className="prose prose-slate max-w-none space-y-12 text-[#3D3D3D]">
          <section>
            <h2 className="text-xl font-bold text-[#0F0F0F] mb-4">1. The Execution Layer Agreement</h2>
            <p className="leading-relaxed">
              By accessing FlowPilot, you are engaging an execution layer for SME treasury operations. These terms govern 
              your use of our platform, AI agents, and integrations with the Interswitch Protocol. We provide the 
              traceability and supervision tools; you provide the strategic direction and final approval.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0F0F0F] mb-4">2. Human-in-the-Loop (Supervised AI)</h2>
            <p className="leading-relaxed">
              FlowPilot operates on a <strong>Human-in-the-Loop</strong> mandate. While our AI agents can automate 
              reconciliation and risk scoring, they cannot execute final payouts without explicit approval from an 
              authorized human operator. You agree that the final responsibility for any financial movement rests 
              with your designated team members.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0F0F0F] mb-4">3. Payout Execution & Traceability</h2>
            <div className="space-y-4">
              <p>When you use FlowPilot to execute payouts via Interswitch, you acknowledge:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Verification:</strong> You are responsible for the validity of recipient bank details.</li>
                <li><strong>Traceability:</strong> Every "run" is logged. Attempting to bypass the supervision layers is a breach of service.</li>
                <li><strong>Limits:</strong> Your execution capacity is subject to the liquidity and limits of your connected Interswitch accounts.</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0F0F0F] mb-4">4. Risk Scoring & Advisory</h2>
            <p className="leading-relaxed">
              FlowPilot's risk scores and reconciliation suggestions are generated by AI models. They are intended for 
              guidance and do not constitute professional financial or legal advice. You must exercise your own 
              discretion before accepting any system-generated recommendation.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0F0F0F] mb-4">5. Operational Conduct</h2>
            <p className="leading-relaxed">
              Users must maintain secure credentials. Sharing "Super Admin" roles across multiple physical users 
              compromises the traceability of the system and is strictly prohibited. You must report any suspected 
              security breach of your treasury dashboard immediately.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0F0F0F] mb-4">6. Liability & Service Continuity</h2>
            <p className="leading-relaxed">
              FlowPilot aims for 99.9% uptime for our execution layer. However, we are not liable for delays 
              caused by third-party bank outages or Interswitch API interruptions. We provide a platform for 
              efficiency; we do not bear liability for the underlying financial decisions made by your entity.
            </p>
          </section>

          <section className="pt-8 border-t border-[#D9D4C8]">
            <p className="text-sm font-medium">
              Need clarification on these terms? Contact our legal operations:
              <a href="mailto:legal@flowpilot.ai" className="ml-1 text-[#e86727] hover:underline">legal@flowpilot.ai</a>
            </p>
          </section>
        </div>
      </article>

      <LandingFooter />
    </main>
  );
}
